// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhkzyeuuwyfxwvihxfng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhoa3p5ZXV1d3lmeHd2aWh4Zm5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NDQxNTEsImV4cCI6MjA2NjMyMDE1MX0.XCoqELX_7EjfaeSSIz1hnFh2rutDbs-QtfvCT_RMUJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);